hydra:
    run:
        dir: ./${alg_name}_results/${env_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
# Env config
alg_name: vanilla_es
seed: 0
env_name: arm
episode_length: 250
policy_hidden_layer_sizes: [64, 64]
# ME config
num_evaluations: 0
num_iterations: 2000
num_samples: 1
fixed_init_state: False
discard_dead: False
# Grid config
grid_shape: [50, 50]
# Log config
log_period: 200
store_repertoire: True
store_repertoire_log_period: 200

# Stochasticity config
num_reevals: 512
log_period_reevals: 200

# ES Parameters
sample_number: 512 # Num samples for gradient estimate
sample_sigma: 0.02
sample_mirror: True # Use mirroring sampling
sample_rank_norm: True # Use normalisation
adam_optimizer: True
learning_rate: 0.01
learning_rate_decay: 1.0  # only applied when no ADAM
l2_coefficient: 0.0  # coefficient for regularisation
