hydra:
    run:
        dir: ./${alg_name}_results/${env_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
# Env config
alg_name: mees
seed: 0
env_name: arm
episode_length: 250
policy_hidden_layer_sizes: [64, 64]
# ME config
num_evaluations: 0
num_iterations: 2000
batch_size: 1 # must be 1 for MEES
num_samples: 1
fixed_init_state: False
discard_dead: False
#Emitter config
iso_sigma: 0.01
line_sigma: 0.1
crossover_percentage: 1.0
# Grid config
grid_shape: [50, 50]
# Log config
log_period: 200
store_repertoire: True
store_repertoire_log_period: 200

# Stochasticity config
num_reevals: 512
log_period_reevals: 200

# ES Parameters
sample_number: 10000
sample_sigma: 0.02
sample_mirror: True
sample_rank_norm: True
num_optimizer_steps: 10
adam_optimizer: True
learning_rate: 0.01
learning_rate_decay: 1.0  # only applied without adam
l2_coefficient: 0.01  # coefficient for regularisation
novelty_nearest_neighbors: 10
last_updated_size: 5
exploit_num_cell_sample: 2
explore_num_cell_sample: 5
use_explore: True
use_exploit: True
